version: '3'
services:
  web:
    build: .
    environment:
      - POSTGRES_HOST=postgres
    volumes:
    - '.:/app'
    depends_on:
    - postgres
    links:
    - postgres
    ports:
    - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
  postgres:
    image: postgres:10.3
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=distriloc
    - POSTGRES_PASSWORD=distriloc
    volumes:
    - ./volumes/postgres/data:/var/lib/postgresql/data
volumes:
  postgres:
