version: '3'
services:
  postgres:
    image: postgres:10.3
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=distriloc
    - POSTGRES_PASSWORD=distriloc
    volumes:
    - ./volumes/postgres/data:/var/lib/postgresql/data
volumes:
  postgres:
