default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= REQUIRED_ENV["POSTGRES_HOST"] %>
  username: <%= REQUIRED_ENV["POSTGRES_USER"] %>
  password: <%= REQUIRED_ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bowling_development
test:
  <<: *default
  database: bowling_test

production:
  <<: *default
  database: bowling_production
  username: bowling
  password: <%= ENV['BOWLING_DATABASE_PASSWORD'] %>
